### PR TITLE
Add Laravel 11 support

### LINKED ISSUE #16: Not install in Laravel 11 (Your requirements could not be resolved to an installable set of packages.)
composer require digikraaft/laravel-review-rating
./composer.json has been updated
Running composer update digikraaft/laravel-review-rating
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - digikraaft/laravel-review-rating[v1.0.0, v2.0.0, ..., v2.0.1] require php ^7.4 -> your php version (8.2.7) does not satisfy that requirement.
    - digikraaft/laravel-review-rating v2.1.0 requires php ^7.4|8.0.* -> your php version (8.2.7) does not satisfy that requirement.
    - digikraaft/laravel-review-rating v2.2.0 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.0).
    - digikraaft/laravel-review-rating[v2.3.0, ..., v2.3.1] require laravel/framework ^8.0|^9.0 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.0).
    - digikraaft/laravel-review-rating v3.0.0 requires laravel/framework ^10.0 -> found laravel/framework[v10.0.0, ..., v10.48.10] but it conflicts with your root composer.json require (^11.0).
    - Root composer.json requires digikraaft/laravel-review-rating * -> satisfiable by digikraaft/laravel-review-rating[v1.0.0, v2.0.0, ..., v2.3.1, v3.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require digikraaft/laravel-review-rating:*" to figure out if any version is installable, or "composer require digikraaft/laravel-review-rating:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### PR DESCRIPTION
**Pull request by dsbilling**
Closes #16

### CODE REVIEW

**Comment by dsbilling** [comment]
@timoladoyinbo Could you take a look at this one?

**Comment by timoladoyinbo** [comment]
Hi,

I will look into this shortly.

Regards,
Tim.

**Comment by sahilcygner** [comment]
> Hi, I will look into this shortly. Regards, Tim.
> […](#)
> On 4 Jun 2024 at 5:03 PM +0100, Daniel S. Billing ***@***.***>, wrote: @timoladoyinbo Could you take a look at this one? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Can you please update this in Composer, I can't build it from your branch.

**Comment by timoladoyinbo** [comment]
Thanks @dsbilling your pull request has been merged and the new release has been [tagged](https://github.com/digikraaft/laravel-review-rating/releases/tag/v3.1.0) 



> @timoladoyinbo Could you take a look at this one?

**Comment by timoladoyinbo** [comment]
Hi, @sahilcygner a new version has been released. You should be able to update without any issues now.

> > Hi, I will look into this shortly. Regards, Tim.
> > […](#)
> > On 4 Jun 2024 at 5:03 PM +0100, Daniel S. Billing _**@**_._**>, wrote: @timoladoyinbo Could you take a look at this one? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.**_>
> 
> Can you please update this in Composer, I can't build it from your branch.

**Pull request merged**
